### PR TITLE
Fixes issue where groups with uppercase worldname created does not work.

### LINKED ISSUE #421: New Groups not taking effect until restart
### Information

* **Server version:** git-Paper-498

* **Full output of `/mv version -p`:** https://j.mp/37QTRQF

* **Server log:** https://paste.gg/p/anonymous/7e3115099ceb4d988e815b9fe00965d3

### Details
I was **`able`** to reproduce my issue on a freshly set up and up-to-date server with the latest versions of Multiverse plugins with no other plugins and with no kinds of other server or client mods.

**Description**
Creating a new group in Multiverse-Inventories does not take effect until a server restart. Prior to 4.2.2, they would not take effect even after a server restart if the player had visited one of the worlds in the group.

**Steps to reproduce**
1. Set up a fresh server with MV Core and Inventories.
2. `/mvc TESTER normal` and `/mvc TESTER_nether nether`.
3. Group the two new worlds and share everything using `/mvinv group`.
4. Visit `TESTER` and add something to your inventory.
5. Visit `TESTER_nether`

**Expected Behavior**
Your inventory should be shared.

**Actual Behavior**
A blank inventory is observed.

**Workaround as of Multiverse-Inventories 4.2.2** (not working on 4.2.1 if the player has visited either world already)
Teleport back to `TESTER`, then restart the server.

### PR DESCRIPTION
**Pull request by benwoo1110**
Fixes #421.

Set from `WorldGroup#getWorlds` should not modified directly. This cause issues with worldname in WorldGroup not being in lowercase.

* Added useful methods to add/remove multiple worlds at once.

* `/mvinv group` should use these methods instead of changing the HashSet of worldnames directly.

### CODE REVIEW

**Comment by nicegamer7** [comment]
Ah I see what's going on. At first I didn't understand why this fixed it, but now I see that in `addWorld` the lowercase world name is added.

File: src/main/java/com/onarandombox/multiverseinventories/command/prompts/GroupWorldsPrompt.java [hunk 1]
```diff
@@ -51,8 +51,8 @@ public Prompt acceptInput(final ConversationContext conversationContext, final S
                 messager.normal(Message.GROUP_WORLDS_EMPTY, sender);
                 return this;
             }
-            group.getWorlds().clear();
-            group.getWorlds().addAll(worlds);
+            group.removeAllWorlds(false);
+            group.addWorlds(worlds, false);
```
Comment (nicegamer7) [inline src/main/java/com/onarandombox/multiverseinventories/command/prompts/GroupWorldsPrompt.java:55]: Why don't you update the config here?

Comment (benwoo1110) [reply src/main/java/com/onarandombox/multiverseinventories/command/prompts/GroupWorldsPrompt.java:55]: Bcu the should update the config after the shares are added when creating a new group.

**Comment by benwoo1110** [comment]
Honestly, dont really like the way its handled, like you can modify the Set with `getWorlds`, but also have methods such as `addWorld` which makes it confusing. Made a more elaborate PR #427 to improve on this. But this should be a good enough fix for now.

File: src/main/java/com/onarandombox/multiverseinventories/command/prompts/GroupWorldsPrompt.java (hunk 1 above)
Comment (nicegamer7) [reply src/main/java/com/onarandombox/multiverseinventories/command/prompts/GroupWorldsPrompt.java:55]: Ah okay, makes sense.

**Review by nicegamer7 — APPROVED** [review]
LGTM 👍.
